/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p3;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Tim
 */
public class ProductDaoImpl extends OracleBaseDao implements ProductDao {

    @Override
    public List<Product> findAll() {
        Connection connection = super.getConnection();
        List<Product> producten = new ArrayList<>();
        String query = "select * from product";
        
        try{
            PreparedStatement statement = connection.prepareStatement(query);
            Product p = new Product();
            
                try (ResultSet rs = statement.executeQuery()) {
                    
                        while (rs.next()) {
                                p.setProductNummer(rs.getInt("PRODUCTNUMMER"));
                                p.setProductNaam(rs.getString("PRODUCTNAAM"));
                                p.setBeschrijving(rs.getString("BESCHRIJVING"));
                                p.setPrijs(rs.getDouble("PRIJS"));
                                producten.add(p);
                        }
		}
        }
        catch(SQLException e){
            e.printStackTrace();
        }
        return producten;
    }
    
    public Product findByOVkaartnummer(int ovnmr){
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Product findByProductNummer(int prdnmr) {
        Connection connection = super.getConnection();
        Product pro = new Product();
        String query = "select * from product WHERE productnummer = '" + prdnmr + "'" ;
        
        try{
            PreparedStatement statement = connection.prepareStatement(query);
                try (ResultSet rs = statement.executeQuery()) {
                    
                    while (rs.next()) {
                            pro.setProductNummer(rs.getInt("PRODUCTNUMMER"));
                            pro.setProductNaam(rs.getString("PRODUCTNAAM"));
                            pro.setBeschrijving(rs.getString("BESCHRIJVING"));
                            pro.setPrijs(rs.getDouble("PRIJS"));
                    }
                }
            }
        catch(SQLException e){
            e.printStackTrace();
        }
        return pro;
        
    }

    @Override
    public Product save(Product prd) {
        Connection connection = super.getConnection();
        String query = "INSERT INTO product (productnummer, productnaam, beschrijving, prijs) VALUES(" + 
                prd.getProductNummer() + 
                ", '" + prd.getProductNaam()  +
                "', '" + prd.getBeschrijving() + "', " +
                prd.getPrijs() + ")";
        try{
            PreparedStatement statement = connection.prepareStatement(query);
            statement.executeQuery();
        }
        catch(SQLException e){
            System.out.println("Save functie mislukt");
            e.printStackTrace();
        }
        return prd;		
    }

    @Override
    public Product update(Product prd) {
        Connection connection = super.getConnection();
        String query = "UPDATE product SET productnummer = "+
                prd.getProductNummer() +", productnaam = '" + 
                prd.getProductNaam() + 
                "', beschrijving = '"+ 
                prd.getBeschrijving() +"', prijs = "+
                prd.getPrijs() +" WHERE productnummer = "+ 
                prd.getProductNummer() +  "";
        try{
            PreparedStatement statement = connection.prepareStatement(query);
            statement.executeQuery();
        }
        catch(SQLException e){
            e.printStackTrace();
        }
        return prd;
    }

    @Override
    public boolean delete(Product prd) {
        Connection connection = super.getConnection();
        String query = "DELETE FROM product WHERE productnummer = " + prd.getProductNummer() + "";
        
		try {
			
			PreparedStatement statement = connection.prepareStatement(query);
			statement.executeQuery();	
			return true;
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return false;
    }

    @Override
    public void closeConnection() {
        try {
            super.CloseConnection();
        } catch (SQLException ex) {
            Logger.getLogger(ProductDaoImpl.class.getName()).log(Level.SEVERE, null, ex);// autogenerated catch block
        }
    }

    @Override
    public ArrayList<Product> findProductByOvkaart(int ovkaart) {
        ArrayList<Product> producten = new ArrayList<Product>();
        String query = "SELECT * from ov_chipkaart_product WHERE kaartnummer= " + ovkaart+ "";
        Connection connection = super.getConnection();
        try {
                PreparedStatement statement = connection.prepareStatement(query);
                Product p = new Product();
                try (ResultSet rs = statement.executeQuery()) {
                        while (rs.next()) {
                                p.setProductNummer(rs.getInt("PRODUCTNUMMER"));
                                p.setProductNaam(rs.getString("PRODUCTNAAM"));
                                p.setBeschrijving(rs.getString("BESCHRIJVING"));
                                p.setPrijs(rs.getDouble("PRIJS"));
                                producten.add(p);
                        }
                } 
        } catch (SQLException e) {
                e.printStackTrace();
        }

        return producten;
    }
    
}
